ru_select_ore db "Выбери руду:", 13, 10, 0
ru_red_diamonds_ore db "1) Красные алмазы.", 13, 10, 0
ru_sky_crystals_ore db "2) Небесные кристаллы.", 13, 10, 0
ru_hell_crystals_ore db "3) Адские кристаллы.", 13, 10, 0
ru_wolfram_ore db "4) Вольфрам.", 13, 10, 0
ru_red_netherite_ore db "5) Красный незерит.", 13, 10, 0
ru_red_diamond_message:
    db "$dКрасные алмазы.", 10
    db "Спавн: $gОбычный мир$d, от $r-64$d до $g30$d по Y.", 10
    db "Добыча: $cАлмазная$d кирка и выше.", 0
ru_sky_crystal_message:
    db "$dНебесные кристаллы.", 10
    db "Спавн: $gОбычный мир$d, от $r-60$d до $g60$d по Y.", 10
    db "Добыча: $cАлмазная$d кирка и выше.", 0
ru_hell_crystal_message:
    db "$dАдские кристаллы.", 10
    db "Спавн: $rНезер$d, от $r20$d до $g60$d по Y.", 10
    db "Добыча: $cАлмазная кирка$d и выше.", 0
ru_wolfram_message:
    db "$dВольфрам.", 10
    db "Спавн: $rНезер$d, от $r40$d до $g120$d по Y.", 10
    db "Добыча: $sНезеритовая$d кирка и выше.", 0
ru_red_netherite_message:
    db "$dКрасный незерит.", 10
    db "Спавн: $rНезер$d, от $r0$d до $g30$d по Y.", 10
    db "Добыча: Кирка $r5 уровня добычи$d и выше.", 0