en_select_drink db "Select a drink:", 13, 10, 0
en_cup_of_tea_drink db "1) Cup of Tea.", 13, 10, 0
en_cup_of_cocoa_drink db "2) Cup of Cocoa.", 13, 10, 0
en_cup_of_coffee_drink db "3) Cup of Coffee.", 13, 10, 0
en_cup_of_lemonade_drink db "4) Cup of Lemonade.", 13, 10, 0
en_rainbow_cocktail_drink db "5) Rainbow Cocktail.", 13, 10, 0
en_cup_of_tea_message:
    db "$dDrinks.", 10
    db "Cup of Tea:", 10
    db "    Crafting: 2 grass, 1 any flower, 1 pink petal, 1 cup.", 10
    db "    $gBuffs$d:", 10
    db "        Regeneration III - 0:15.", 10
    db "    $rNo debuffs.$d", 10
    db "    $cHunger points$d: +1.", 10
    db "    $yStack size$d: 16.", 0
en_cup_of_cocoa_message:
    db "$dCup of Cocoa:", 10
    db "    Crafting: 3 cocoa beans, 3 sugar, 1 cup.", 10
    db "    $gBuffs$d:", 10
    db "        Regeneration - 0:15;", 10
    db "        Resistance - 0:05.", 10
    db "    $rNo debuffs.$d", 10
    db "    $cHunger points$d: +2.", 10
    db "    $yStack size$d: 16.", 0
en_cup_of_coffee_message:
    db "$dCup of Coffee:", 10
    db "    Crafting: 6 cocoa beans, 2 sugar, 1 cup.", 10
    db "    $gBuffs$d:", 10
    db "        Speed II - 0:15;", 10
    db "        Haste - 0:15.", 10
    db "    $rNo debuffs.$d", 10
    db "    $cHunger points$d: +2.", 10
    db "    $yStack size$d: 16.", 0
en_cup_of_lemonade_message:
    db "$dCup of Lemonade:", 10
    db "    Crafting: 4 lemons, 4 sugar, 1 cup.", 10
    db "    $gBuffs$d:", 10
    db "        Night Vision - 0:15;", 10
    db "        Resistance - 0:05.", 10
    db "    $rNo debuffs.$d", 10
    db "    $cHunger points$d: +1.", 10
    db "    $yStack size$d: 16.", 0
en_rainbow_cocktail_message:
    db "$dRainbow Cocktail:", 10
    db "    Crafting: 2 echo shards, 4 warden hearts, 2 enchanted golden apples, 1 bottle.", 10
    db "    $gBuffs$d:", 10
    db "        Resistance II - 10:00;", 10
    db "        Absorption V - 10:00;", 10
    db "        Fire Resistance - 10:00;", 10
    db "        Regeneration III - 10:00;", 10
    db "        Strength II - 10:00;", 10
    db "        Speed III - 10:00;", 10
    db "        Water Breathing - 10:00;", 10
    db "        Night Vision - 10:00;", 10
    db "    $rNo debuffs.$d", 10
    db "    $cHunger points$d: +10.", 10
    db "    $yStack size$d: 1.", 0