en_select_food db "Select food:", 13, 10, 0
en_lemon_food db "1) Lemon.", 13, 10, 0
en_fried_flesh_food db "2) Fried Flesh.", 13, 10, 0
en_berry_pie_food db "3) Berry Pie.", 13, 10, 0
en_soups_food db "4) Soups.", 13, 10, 0
en_shawarma_food db "5) Shawarma.", 13, 10, 0
en_pink_gold_carrot_food db "6) Pink-Gold Carrot.", 13, 10, 0
en_pink_gold_apple_food db "7) Pink-Gold Apple.", 13, 10, 0
en_enchanted_pink_gold_apple_food db "8) Enchanted Pink-Gold Apple.", 13, 10, 0
en_drinks db "9) Drinks.", 13, 10, 0
en_lemon_message:
    db "$dLemon.", 10
    db "No crafting recipe. Drops from lemon tree leaves.", 10
    db "$gNo buffs.$d", 10
    db "$rDebuffs$d: reduces saturation by 1.", 10
    db "$cHunger points$d: +0.5.", 10
    db "$yStack size$d: 64.", 0
en_fried_flesh_message:
    db "$dFried Flesh.", 10
    db "Crafting: Smelt rotten flesh in a furnace or smoker.", 10
    db "$gNo buffs.$d", 10
    db "$rNo debuffs.$d", 10
    db "$cHunger points$d: +2.5.", 10
    db "$yStack size$d: 64.", 0
en_berry_pie_message:
    db "$dBerry Pie.", 10
    db "Crafting: 2 eggs, 1 milk bucket, 3 wheat, 3 sweet berries.", 10
    db "$gNo buffs.$d", 10
    db "$rNo debuffs.$d", 10
    db "$cHunger points$d: +5.", 10
    db "$yStack size$d: 64.", 0
en_soups_message:
    db "$dSoups.", 10
    db "$gNo buffs.$d", 10
    db "$rNo debuffs.$d", 10
    db "Cabbage Soup:", 10
    db "    Crafting: 3 seagrass, 1 bowl, 1 kelp, 3 sea pickles.", 10
    db "    $cHunger points$d: +3.", 10
    db "    $yStack size$d: 16.", 10
    db "", 10
    db "Chicken Soup:", 10
    db "    Crafting: 2 potatoes, 1 seagrass, 1 carrot, 1 bowl, 1 kelp, 1 chicken.", 10
    db "    $cHunger points$d: +5.", 10
    db "    $yStack size$d: 16.", 10
    db "", 10
    db "Fish Soup:", 10
    db "    Crafting: 1 potato, 1 seagrass, 1 carrot, 1 kelp, 1 bowl, 1 sea pickle, 1 cod, 1 salmon.", 10
    db "    $cHunger points$d: +5.", 10
    db "    $yStack size$d: 16.", 0
en_shawarma_message:
    db "$dShawarma.", 10
    db "$gNo buffs.$d", 10
    db "$rNo debuffs.$d", 10
    db "Chicken:", 10
    db "    Crafting: 1 iron nugget, 1 cooked chicken, 1 baked potato, 1 kelp, 1 bread.", 10
    db "    $cHunger points$d: +4.", 10
    db "    $yStack size$d: 16.", 10
    db "", 10
    db "Beef:", 10
    db "    Crafting: 1 iron nugget, 1 steak, 1 baked potato, 1 kelp, 1 bread.", 10
    db "    $cHunger points$d: +5.", 10
    db "    $yStack size$d: 16.", 10
    db "", 10
    db "Pork:", 10
    db "    Crafting: 1 iron nugget, 1 cooked porkchop, 1 baked potato, 1 kelp, 1 bread.", 10
    db "    $cHunger points$d: +5.", 10
    db "    $yStack size$d: 16.", 10
    db "", 10
    db "Mutton:", 10
    db "    Crafting: 1 iron nugget, 1 cooked mutton, 1 baked potato, 1 kelp, 1 bread.", 10
    db "    $cHunger points$d: +4.", 10
    db "    $yStack size$d: 16.", 10
    db "", 10
    db "Mixed:", 10
    db "    Crafting: 1 iron nugget, 1 of each cooked Minecraft meat, 1 baked potato, 1 kelp, 1 bread.", 10
    db "    $cHunger points$d: +7.", 10
    db "    $yStack size$d: 16.", 0
en_pink_gold_carrot_message:
    db "$dPink-Gold Carrot.", 10
    db "Crafting: 1 golden carrot, 8 pink gold nuggets.", 10
    db "$gNo buffs.$d", 10
    db "$rNo debuffs.$d", 10
    db "$cHunger points$d: +4.", 10
    db "$yStack size$d: 64.", 0
en_pink_gold_apple_message:
    db "$dPink-Gold Apple.", 10
    db "Crafting: 1 golden apple, 8 pink gold ingots.", 10
    db "$gBuffs$d:", 10
    db "    Absorption IV - 2:30;", 10
    db "    Regeneration IV - 0:15;", 10
    db "    Resistance I - 2:30.", 10
    db "$rNo debuffs.$d", 10
    db "$cHunger points$d: +4.", 10
    db "$yStack size$d: 64.", 0
en_enchanted_pink_gold_apple_message:
    db "$dEnchanted Pink-Gold Apple.", 10
    db "Crafting:", 10
    db "    - 1 golden apple, 8 pink gold blocks.", 10
    db "        or", 10
    db "    - 1 enchanted golden apple, 8 pink gold ingots.", 10
    db "$gBuffs$d:", 10
    db "    Resistance III - 5:00;", 10
    db "    Absorption V - 5:00;", 10
    db "    Strength II - 5:00;", 10
    db "    Fire Resistance - 5:00;", 10
    db "    Regeneration VI - 0:15.", 10
    db "        $s*followed by Regeneration III - 4:45*$d", 10
    db "$rNo debuffs.$d", 10
    db "$cHunger points$d: +6.", 10
    db "$yStack size$d: 64.", 0