en_select_ore db "Select an ore:", 13, 10, 0
en_red_diamonds_ore db "1) Red Diamonds.", 13, 10, 0
en_sky_crystals_ore db "2) Sky Crystals.", 13, 10, 0
en_hell_crystals_ore db "3) Hell Crystals.", 13, 10, 0
en_wolfram_ore db "4) Tungsten.", 13, 10, 0
en_red_netherite_ore db "5) Red Netherite.", 13, 10, 0
en_red_diamond_message:
    db "$dRed Diamonds.", 10
    db "Spawn: $gOverworld$d, from $r-64$d to $g30$d Y.", 10
    db "Mining: $cDiamond$d pickaxe or better.", 0
en_sky_crystal_message:
    db "$dSky Crystals.", 10
    db "Spawn: $gOverworld$d, from $r-60$d to $g60$d Y.", 10
    db "Mining: $cDiamond$d pickaxe or better.", 0
en_hell_crystal_message:
    db "$dHell Crystals.", 10
    db "Spawn: $rNether$d, from $r20$d to $g60$d Y.", 10
    db "Mining: $cDiamond$d pickaxe or better.", 0
en_wolfram_message:
    db "$dTungsten.", 10
    db "Spawn: $rNether$d, from $r40$d to $g120$d Y.", 10
    db "Mining: $sNetherite$d pickaxe or better.", 0
en_red_netherite_message:
    db "$dRed Netherite.", 10
    db "Spawn: $rNether$d, from $r0$d to $g30$d Y.", 10
    db "Mining: Pickaxe with $rMining Level 5$d or better.", 0