section .text
lang_ru:
; назад
    set_lang ru_back, back
; основное меню
    set_lang ru_at_guide, at_guide
    set_lang ru_ore_info, ore_info
    set_lang ru_food_info, food_info
    set_lang ru_tool_info, tool_info
    set_lang ru_app_info, app_info
    set_lang uni_lang_pick, pick_lang
    set_lang ru_main_exit, main_exit

; меню руд
    set_lang ru_select_ore, select_ore
    set_lang ru_red_diamonds_ore, red_diamonds_ore
    set_lang ru_sky_crystals_ore, sky_crystals_ore
    set_lang ru_hell_crystals_ore, hell_crystals_ore
    set_lang ru_wolfram_ore, wolfram_ore
    set_lang ru_red_netherite_ore, red_netherite_ore
    set_lang ru_exit, ore_exit
    ; меню руд(сообщения)
    set_lang ru_red_diamond_message, red_diamond_message
    set_lang ru_sky_crystal_message, sky_crystal_message
    set_lang ru_hell_crystal_message, hell_crystal_message
    set_lang ru_wolfram_message, wolfram_message
    set_lang ru_red_netherite_message, red_netherite_message

; меню еды
    set_lang ru_select_food, select_food
    set_lang ru_lemon_food, lemon_food
    set_lang ru_fried_flesh_food, fried_flesh_food
    set_lang ru_berry_pie_food, berry_pie_food
    set_lang ru_soups_food, soups_food
    set_lang ru_shawarma_food, shawarma_food
    set_lang ru_pink_gold_carrot_food, pink_gold_carrot_food
    set_lang ru_pink_gold_apple_food, pink_gold_apple_food
    set_lang ru_enchanted_pink_gold_apple_food, enchanted_pink_gold_apple_food
    set_lang ru_drinks, drinks
    set_lang ru_exit, food_exit
    ; меню еды(сообщения)
    set_lang ru_lemon_message, lemon_message
    set_lang ru_fried_flesh_message, fried_flesh_message
    set_lang ru_berry_pie_message, berry_pie_message
    set_lang ru_soups_message, soups_message
    set_lang ru_shawarma_message, shawarma_message
    set_lang ru_pink_gold_carrot_message, pink_gold_carrot_message
    set_lang ru_pink_gold_apple_message, pink_gold_apple_message
    set_lang ru_enchanted_pink_gold_apple_message, enchanted_pink_gold_apple_message

; меню напитков
    set_lang ru_select_drink, select_drink
    set_lang ru_cup_of_tea_drink, cup_of_tea_drink
    set_lang ru_cup_of_cocoa_drink, cup_of_cocoa_drink
    set_lang ru_cup_of_coffee_drink, cup_of_coffee_drink
    set_lang ru_cup_of_lemonade_drink, cup_of_lemonade_drink
    set_lang ru_rainbow_cocktail_drink, rainbow_cocktail_drink
    set_lang ru_exit, drink_exit
    ; меню напитков(сообщения)
    set_lang ru_cup_of_tea_message, cup_of_tea_message
    set_lang ru_cup_of_cocoa_message, cup_of_cocoa_message
    set_lang ru_cup_of_coffee_message, cup_of_coffee_message
    set_lang ru_cup_of_lemonade_message, cup_of_lemonade_message
    set_lang ru_rainbow_cocktail_message, rainbow_cocktail_message

; меню брони и инструментов
    set_lang ru_select_material, select_material
    set_lang ru_copper_material, copper_material
    set_lang ru_lapis_material, lapis_material
    set_lang ru_pink_gold_material, pink_gold_material
    set_lang ru_amethyst_material, amethyst_material
    set_lang ru_redstone_material, redstone_material
    set_lang ru_quartz_material, quartz_material
    set_lang ru_emerald_material, emerald_material
    set_lang ru_red_diamond_material, red_diamond_material
    set_lang ru_sky_crystal_material, sky_crystal_material
    set_lang ru_hell_crystal_material, hell_crystal_material
    set_lang ru_wolfram_material, wolfram_material
    set_lang ru_red_netherite_material, red_netherite_material
    set_lang ru_enderite_material, enderite_material
    set_lang ru_exit, armor_exit
    ; меню брони и инструментов(сообщения)
    set_lang ru_copper_material_message, copper_material_message
    set_lang ru_lapis_material_message, lapis_material_message
    set_lang ru_pink_gold_material_message, pink_gold_material_message
    set_lang ru_amethyst_material_message, amethyst_material_message
    set_lang ru_redstone_material_message, redstone_material_message
    set_lang ru_quartz_material_message, quartz_material_message
    set_lang ru_emerald_material_message, emerald_material_message
    set_lang ru_red_diamond_material_message, red_diamond_material_message
    set_lang ru_sky_crystal_material_message, sky_crystal_material_message
    set_lang ru_hell_crystal_material_message, hell_crystal_material_message
    set_lang ru_wolfram_material_message, wolfram_material_message
    set_lang ru_red_netherite_material_message_1, red_netherite_material_message_1
    set_lang ru_red_netherite_material_message_2, red_netherite_material_message_2
    set_lang ru_enderite_material_message_1, enderite_material_message_1
    set_lang ru_enderite_material_message_2, enderite_material_message_2
; информация о моде и приложении
    set_lang ru_mod_info_message, mod_info_message
    ret